name: MapControl
version: '${project.version}'
main: com.thistles.mapcontrol.Main

#depend: [LuckPerms]

commands:
  mapcontrol:
    aliases: [map]
    description: Manage filled maps on your server.
    usage: /mapcontrol <clear>|<unlock>|<tp>|<get>
#    permission: mapcontrol.use