name: MapControl
version: '${plugin.version}'
author: Thistles
main: com.thistles.common.Main
api-version: 1.18

commands:
  mapcontrol:
    aliases: [map]
    permission: mapcontrol.use
    description: Manage filled maps on your server.
    usage: /<command> <action>

mapcontrol:
  mapcontrol.use:
    description: Access to all mapcontrol functions