name: MapControl
version: '${project.version}'
main: com.thistles.common.Main
api-version: 1.18

commands:
  mapcontrol:
    aliases: [map]
    description: Manage filled maps on your server.
    usage: /<command> <action>
